# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]


permissions:
  contents: read

jobs:
  run-backend:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: run main
      run: |
        cd src
        python main.py


